apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubepro-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubepro
  template:
    metadata:
      labels:
        app: kubepro
    spec:
      containers:
        - name: kubepro
          image: rachitroy/villa-website
          ports:
            - containerPort: 80
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Served by $(hostname)" >> /usr/share/nginx/html && \
              httpd-foreground
